### ISSUE TITLE
could u support more dataset 

### ISSUE THREAD

**Issue by Yefeiyang-luis** [rtmaww/EntLM#1]
could u support movie ontonote etc data 5---50 shot data. and the dev dataset ,plz

**Comment by Yefeiyang-luis** [comment]
and whether you use the  same size of 5-shot  to dev dataset size.i not find in the code

**Comment by rtmaww** [comment]
Hello. The OntoNotes sampled sets are updated. 
In this code we do not use a dev set, and the results reported can be obtained by testing the model at the last training epoch.

**Comment by Yefeiyang-luis** [comment]
> Hello. The OntoNotes sampled sets are updated. In this code we do not use a dev set, and the results reported can be obtained by testing the model at the last training epoch.

thank u for reply, another problem: what version you choose about mit-movie dataset,the file trivia10k13train.bio or engtrain.bio ...  if the first one ,Quote entity or Opinion entity is hard to choose the single word. any trick for this dataset plz!

**Comment by rtmaww** [comment]
Hello. We use the engtrain.bio in MIT-Movie.
