### ISSUE TITLE
作者能公布一下mitmovie的数据集吗，或者mitmovie的distant数据集

### ISSUE THREAD

**Issue by Yefeiyang-luis** [rtmaww/EntLM#5]
bond的作者没有公布mitmovie的distant数据，而且邮件也联系不上

**Comment by rtmaww** [comment]
你好，MITMovie的distant数据是我们自己构造的，方便的话请留个邮箱，我邮件发送给你

**Comment by Yefeiyang-luis** [comment]
> 你好，MITMovie的distant数据是我们自己构造的，方便的话请留个邮箱，我邮件发送给你

我的邮箱是feiyangye@zjut.edu.cn，非常感谢！

**Comment by lvminghan1997** [comment]
> 你好，MITMovie的distant数据是我们自己构造的，方便的话请留个邮箱，我邮件发送给你

您好，请问能否提供关于movie 的few shot 数据集，万分感激，lvminghan@jxnu.edu.cn

**Comment by zzpw** [comment]
> 你好，MITMovie的distant数据是我们自己构造的，方便的话请留个邮箱，我邮件发送给你

您好，我对您的工作非常感兴趣，方便的话，请问能否提供一下 MITMovie 的数据集，非常感谢，我的邮箱是 pwuzeng@gmail.com
